### ISSUE TITLE
GbEvents Routing 

### ISSUE THREAD

**Issue by mtness** [in2code-de/gb_events#7]
Hi there,
I just discovered that the routing configuration for this extension is nowhere to be found easily...
(yeah of course, we can write it ourselves...) which I did, so here you are to get you started:

```yaml
#[...]
routeEnhancers:
#[...]
  Events:
    type: Extbase
    extension: GbEvents
    plugin: Main
    defaultController: 'GbEvents::list'
    routes:
      - routePath: '/{gbevents-title}'
        _controller: 'Event::show'
        _arguments:
          gbevents-title: event
    aspects:
      gbevents-title:
        type: PersistedAliasMapper
        tableName: tx_gbevents_domain_model_event
        routeFieldName: path_segment
#[...]
```

Best regards,
MT
